### ISSUE TITLE
Look into displaying numbers and other Latex based info onto Github 

### ISSUE THREAD

**Issue by chakrakan** [chakrakan/kattis#1]
Currently, the scraped problem info results in documents with portions that are unreadable

**Comment by TanveshT** [comment]
FIxed this problem to a certain level like the latex symbols `\leq`, `\geq`, `\ldots` and `$` but a more efficient technique can be used but I haven't looked it. I have added this in the pull request I made. Do check the READMEs of the problems created by the new `problem_importer.py` file

**Comment by chakrakan** [comment]
keeping this open for now since I think we can probably use a dictionary to hold most common latex representations as keys with text based values to be used as replacement and simply iterate over `problem_info` string and replace instances with corresponding values
